/**
 * Created by sam on 6/7/17.
 */

export const ADD_CHARACTER = "ADD_CHARACTER";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const EDIT_CHARACTER = "EDIT_CHARACTER";

export const CHARACTER_ADD_VALUE = "CHARACTER_ADD_VALUE";
export const CHARACTER_EDIT_VALUE = "CHARACTER_EDIT_VALUE";